### ISSUE TITLE
Create MIDI file with PDF (or preview)

### ISSUE THREAD

**Issue by ddugovic** [ettolrach/open-lilybot#4]
To create a MIDI output file from a LilyPond file, insert a `\midi` block inside a `\score` block.
http://lilypond.org/doc/v2.18/Documentation/notation/creating-midi-files

    $lilypond -dpreview ```\score { { \clef bass e,8 e e, e e, e e, e } \layout { } \midi { \tempo 4 = 120 } }``` $v

    $lilypond -dpreview ```\score { { \clef bass e,8 e e, e e, e e, e } \midi { \tempo 4 = 120 } }``` $v

**Comment by ettolrach** [comment]
That is correct. I was thinking of somehow combining it with the PDF or PNG preview, but I think it's simpler to just have the user run two commands than to try and do anything fancy. Thank you.
